name: Build Docker images push to Docker Hub

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      version_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Login docker hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4
      - name: Git config
        run: |
          git config --global --add safe.directory /__w/kairos/kairos

      - name: Set Docker Tag
        id: set-docker-tag
        run: |
          echo "docker_tag=${{ inputs.version_name }}_${{ inputs.tag_name }}" >> $GITHUB_OUTPUT

      - name: Build images
        run: |
          export DOCKER_TAG=${{ steps.set-docker-tag.outputs.docker_tag }}
          docker build --tag kairos:$DOCKER_TAG .
          docker image tag kairos:$DOCKER_TAG overfoundation/kairos:$DOCKER_TAG

      - name: Push image to Docker Hub
        run: |
          docker push overfoundation/kairos:${{ steps.set-docker-tag.outputs.docker_tag }}

      - name: Push latest image to Docker Hub
        if: ${{ inputs.tag_name == 'stable' }}
        run: |
          docker push overfoundation/kairos:latest
