name: Go Test Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - run: make test
